# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "68778a21adf35f3a33e0a91f070394d4"
name = "dot-export-dev"
handle = "dot-export-dev-1"
application_url = "https://secrets-giant-lithuania-au.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sleeping-dawn.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,write_products"

[auth]
redirect_urls = [
  "https://secrets-giant-lithuania-au.trycloudflare.com/auth/callback",
  "https://secrets-giant-lithuania-au.trycloudflare.com/auth/shopify/callback",
  "https://secrets-giant-lithuania-au.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
